# Generated by Django 3.0.2 on 2020-05-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('Employee_code', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=150)),
                ('birth', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.Position')),
            ],
        ),
    ]
