# Generated by Django 3.0.2 on 2020-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeinfo_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to='media'),
        ),
    ]
