# Generated by Django 3.0.2 on 2020-05-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200503_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
