# Generated by Django 3.0.2 on 2020-05-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200503_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='thumb',
        ),
    ]
